version: "3"
services:
  cassandra:
    image: bitnami/cassandra:latest
    container_name: cassandra
    networks:
      - cassandra_network
    ports:
      - 9042:9042

networks:
  cassandra_network: {}
